jaswdr/faker

- company.go
fixes https://github.com/jaswdr/faker/issues/5
> fix: Company.BS() using catch phrase words

- faker.go
- mimetype.go
- mimetype_test.go
adding mime-types generator
ref #13
> added mime-type generator

- faker.go
- youtube.go
- youtube_test.go
Hello,
This PR addresses #13 
Happy to discuss as needed.
Thank you.
> introduce a new YouTube fake URL Generator

- faker.go
- faker_test.go
Example:
```go
willBeTrueWith30PercentChance := f.BoolChanced(30)
```
> Added BoolChanced() function

- address.go
- color.go
- company.go
- faker.go
- image.go
- internet.go
- lorem.go
- mimetype.go
- payment.go
- person.go
- phone.go
- time.go
- user_agent.go
- uuid.go
- youtube.go
background: I am experimenting with my AST-based GoDoc generator tool for this, the current template goes like this
1. struct -> `[struct_name] is a faker struct for [struct_name]`
2. methods -> `[function_name] returns a fake [function_name] for [struct_name]`
feel free to:
1. close the PR if you're looking for better docs
2. suggest a better template comment if you think this way is fine
P.S some of the files are not commented because of a bug in my tool which I'm still trying to figure out
> add template docstring

- .travis.yml
- README.md
Adding coverage report to [coveralls.io](https://coveralls.io/github/jaswdr/faker)
It's a new feature to track the increase or decrease of coverage per change
**Go Version**
Don't apply, there is no change in Go code
**Go Tests**
Don't apply, there is no change in Go code
> Feature coveralls report

- boolean.go
- boolean_test.go
- faker.go
- faker_test.go
- internet.go
- adding IntBoolean, StringBoolean
- replacement bool faker from faker file (code from others from the previous PR)
example usage
```
faker := faker.New()
boolean := faker.Boolean().Bool()
booleanWithChance := faker.Boolean().BoolWithChance(50)
integer := faker.Boolean().IntBool()
stringg := faker.Boolean().StringBool("yes", "no")
fmt.Println(boolean, integer, stringg, booleanWithChance) // return: true 0 yes false
```
> [ADD & REFACTOR] Boolean, IntBoolean, StringBoolean faker

- README.md
Adding a link to the Discussions panel for questions
Don't apply
**Go Version**
Don't apply
**Go Tests**
Don't apply
> Add Discussions link to README

- faker.go
- loremflickr.go
- loremflickr_test.go
Adding LoremFlickr support as suggested by @FournyP in #50
Adding new generator to create fake images using the remote service LoremFlickr
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test -v
PASS
ok      github.com/jaswdr/faker 0.222s
```
> Adding generator for LoremFlickr

- README.md
- pull_request_template.md
Currently, there are two external image generators supported, LoremFlickr and ThisPersonDoesNotExist, this PR adds some examples in README to show how to use them.
Improve documentation about Image generators
**Go Version**
Don't apply
**Go Tests**
Don't apply
> Document external image generators

- lorem_flickr.go
- profile_image.go
- utils.go
Fixing Codacy static analyser violations.
Codacy violations.
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 0.988s
```
> Fix Codacy violations

- .github/workflows/coverage.yml
- .github/workflows/test.yml
- README.md
Adding Codecov reporting.
Reporting the coverage of tests to Codecov.
**Go Version**
```
$ go version
go version go1.17.6 linux/amd64
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 0.887s
```
> Updated README with relevant links

- crypto.go
- crypto_test.go
- faker.go
Added Bitcoin address generation based on discussion in #78 
#78 
**Go Version**
```
abc@c63bccef3747:~/workspace/oss/faker$ go version
go version go1.17.3 linux/amd64
```
**Go Tests**
```
abc@c63bccef3747:~/workspace/oss/faker$ go test
PASS
ok      github.com/jaswdr/faker 5.644s
abc@c63bccef3747:~/workspace/oss/faker$ 
```
> feat: added Bitcoin address generation

- .licrc
- address.go
- company.go
- company_test.go
- currency_test.go
- faker.go
- image.go
- image_test.go
- internet.go
- lorem_flickr.go
- lorem_flickr_test.go
- music.go
- payment.go
- person.go
- person_test.go
- phone.go
- profile_image.go
- profile_image_test.go
- utils.go
- utils_test.go
Replace this line with a short description of your changes
Improve code coverage to catch more errors and make coverage predictable.
**Go Version**
```
$ go version
go version go1.17.6 linux/amd64
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 0.702s
```
> Improving code coverage

- .github/workflows/test.yml
Including Go 1.18.x in test matrix.
No
**Go Version**
N/A
**Go Tests**
N/A
> Adding Go 1.18.x to test matrix

- crypto.go
- crypto_test.go
- currency_test.go
Refactoring existing Crypto generator to align with the project standards.
Also, fixing Currency test by removing check for empty string in currency code, since it is a value.
No.
**Go Version**
```
$ go version
go version go1.18.3 linux/amd64
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 1.397s
```
> Refactoring Crypto generator

- color_test.go
N/A
Fixing #120
**Go Version**
```
$ go version
go version go1.18.4 linux/amd64
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 0.909s
```
> Fixes value assigned to a variable is never read before being overwritten in color test

- address.go
- address_test.go
Add country code
No
**Go Version**
```
$ go version
go version go1.19.4 darwin/arm64
```
**Go Tests**
```
$ go test
2022/12/22 16:06:48 Error while requesting https://loremflickr.com/300/200 : request failed
2022/12/22 16:06:48 Error while creating a temp file: temp file creation failed
2022/12/22 16:06:49 Error while requesting https://thispersondoesnotexist.com/image : request failed
2022/12/22 16:06:49 Error while creating a temp file: temp file creation failed
PASS
ok  	github.com/jaswdr/faker	2.145s
```
> add countryCode

- address.go
Fix return variable name in longitude function
**Go Version**
```shell
$ go version
go version go1.19.7 linux/amd64
```
**Go Tests**
```shell
$ go test
2023/04/13 00:05:55 Error while requesting https://loremflickr.com/300/200 : request failed
2023/04/13 00:05:56 Error while creating a temp file: temp file creation failed
2023/04/13 00:05:56 Error while requesting https://randomuser.me : request failed
2023/04/13 00:05:56 Error while creating a temp file: temp file creation failed
PASS
ok      github.com/jaswdr/faker 5.290s
```
> Update longitude return variable name

- uuid.go
- uuid_test.go
Fix return value of UUID V4
**Go Version**
```
$ go version
go version go1.19.8 darwin/amd64
```
**Go Tests**
```
$ go test
2023/05/06 21:11:33 Error while requesting https://loremflickr.com/300/200 : request failed
2023/05/06 21:11:34 Error while creating a temp file: temp file creation failed
2023/05/06 21:11:35 Error while requesting https://randomuser.me : request failed
2023/05/06 21:11:35 Error while creating a temp file: temp file creation failed
PASS
ok      github.com/jaswdr/faker 12.356s
```
> fix: UUID V4 generation

- .github/workflows/test.yml
This changes adds Go 1.20 to the test matrix.
NA
**Go Version**
NA
**Go Tests**
NA
> Adds Go 1.20 to the test matrix

- internet.go
Cache Internet.User() firstname/lastname to prevent string operations at runtime.
> internet: cache Internet.User() first/last names

- crypto.go
- crypto_test.go
Revert previous change that makes the Crypto generator less random.
N/A
**Go Version**
```
$ go version
go version go1.19 darwin/amd64
```
**Go Tests**
```
$ go test
2023/10/10 10:36:20 Error while requesting https://loremflickr.com/300/200 : request failed
2023/10/10 10:36:21 Error while creating a temp file: temp file creation failed
2023/10/10 10:36:21 Error while requesting https://randomuser.me : request failed
2023/10/10 10:36:21 Error while creating a temp file: temp file creation failed
PASS
ok  	github.com/jaswdr/faker	4.138s
```
> Revert changes done to crypto to make it less random

- README.md
Add dummy change to purge cache of cover.png image.
N/A
**Go Version**
N/A
**Go Tests**
N/A
> Purge cover.png cache

- README.md
- go.mod
Setup of V2 in go.mod and README
N/A
**Go Version**
```
$ go version
go version go1.21.6 linux/amd64
```
**Go Tests**
```
$ go test
2024/01/20 11:44:00 Error while requesting https://loremflickr.com/300/200 : request failed
2024/01/20 11:44:00 Error while creating a temp file: temp file creation failed
2024/01/20 11:44:00 Error while requesting https://randomuser.me : request failed
2024/01/20 11:44:00 Error while creating a temp file: temp file creation failed
PASS
ok  	github.com/jaswdr/faker/v2	2.144s
```
> V2 package

- .github/workflows/test.yml
Adding Go 1.22 to matrix of tests.
N/A
**Go Version**
N/A
**Go Tests**
N/A
> Adding tests for 1.22

- README.md
Update the code in the Go playground link to V2.
N/A
**Go Version**
N/A
**Go Tests**
N/A
> Update the code in the Go playground link to V2

- utils.go
- utils_test.go
- Added a generic Shuffle function to randomly reorder elements in a slice.
- Introduced tests for Shuffle to ensure functionality with multiple elements and a single element case.
#123 
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker/v2      2.298s
```
> feat: Implement Shuffle function and add corresponding tests

- README.md
Removing since the tool got discontinued.
**Go Version**
N/A
**Go Tests**
N/A
> Removed hit count from README

- faker.go
Replaced manual reversal of string slice with a call to the generic Shuffle function
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker/v2      2.318s
```
> refactor: Simplify ShuffleString implementation in Faker (#186)

- .github/workflows/test.yml
- binarystring_test.go
- company_test.go
- faker.go
- faker_benchmark_test.go
- iban_test.go
[Replace this line with a short description of your changes](refactor: Remove unused benchmark tests and improve random number generation)
#169 
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker/v2      2.627s
```
> refactor: Remove unused benchmark tests and improve random number generation

- faker.go
- faker_test.go
Add NewWithSeedInt64 function and corresponding test
#132 
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker/v2      2.687s
```
> feat: Add NewWithSeedInt64 function and corresponding test

- struct.go
Address issues identified in latest [DeepSource](https://app.deepsource.com/gh/jaswdr/faker/run/aeedb759-bc09-40e3-b87e-684e94c47e2d/go/) run.
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
```
> Fix deepsource

- faker.go
- struct.go
- struct_test.go
- time_test.go
Adding feature to fill a map or pointer to a map or slice
**Go Version**
```
$ go version
go version go1.25.1 darwin/arm64
```
```
$ go test ./...
ok      github.com/jaswdr/faker/v2      7.063s
```
> add fillMap in Struct generator
