company.go
company_test.go

Improvement for `Company.CatchPhrase()` and `Company.BS()`.
Removes the empty space before the generated string, and adds tests for the number of words

fix: Remove space prefix of catchphrase and BS

---

faker.go

With current implementation IntBetween() never returns an index of the last element in the slice.
Probably there are same defects in other parts of the lib.

Fix range to choose random values.

---

time_test.go

Fixes: Issue #19 
The problem is at the comparison of `year > 1970`. The `Year()` function returns an `IntBetween(1970, time.Now().Year)` on [time.go](https://github.com/jaswdr/faker/blob/master/time.go#L136-L138) which makes it possible to return a `1970` year sometimes causing tests to fail randomly.

#19: change comparison operator

---

faker.go
person.go
person_test.go

I imagine if I need gender as fake data but I want the gender still related to her/his name.
I think this code in this PR, not at the top of best practice
example usage
```golang
p := New().Person()
name := p.Name()
gender := p.Gender()
fmt.Println(name, gender)
```

[ADD] gender that related to her/his name

---

internal/test/fake_source.go
internal/test/fake_source_test.go
person.go
person_test.go

100% test coverage for `person.go`.
Includes partial fixes for #28. 
**Go Version**
```
$ go version
go version go1.15.2 linux/amd64
```
**Go Tests**
```
$ go test -v
=== RUN   TestCityPrefix
--- PASS: TestCityPrefix (0.00s)
=== RUN   TestSecondaryAddress
--- PASS: TestSecondaryAddress (0.00s)
=== RUN   TestState
--- PASS: TestState (0.00s)
=== RUN   TestStateAbbr
--- PASS: TestStateAbbr (0.00s)
=== RUN   TestCitySuffix
--- PASS: TestCitySuffix (0.00s)
=== RUN   TestStreetSuffix
--- PASS: TestStreetSuffix (0.00s)
=== RUN   TestBuildingNumber
--- PASS: TestBuildingNumber (0.00s)
=== RUN   TestCity
--- PASS: TestCity (0.00s)
=== RUN   TestStreetName
--- PASS: TestStreetName (0.00s)
=== RUN   TestStreetAddress
--- PASS: …
```

person.go: 100% test coverage

---

faker.go
faker_test.go

Fix #31
#31 
**Go Version**
```
$ go version
go version go1.15 linux/amd64
```
**Go Tests**
```
$ go test -v
=== RUN   TestCityPrefix
--- PASS: TestCityPrefix (0.00s)
=== RUN   TestSecondaryAddress
--- PASS: TestSecondaryAddress (0.00s)
=== RUN   TestState
--- PASS: TestState (0.00s)
=== RUN   TestStateAbbr
--- PASS: TestStateAbbr (0.00s)
=== RUN   TestCitySuffix
--- PASS: TestCitySuffix (0.00s)
=== RUN   TestStreetSuffix
--- PASS: TestStreetSuffix (0.00s)
=== RUN   TestBuildingNumber
--- PASS: TestBuildingNumber (0.00s)
=== RUN   TestCity
--- PASS: TestCity (0.00s)
=== RUN   TestStreetName
--- PASS: TestStreetName (0.00s)
=== RUN   TestStreetAddress
--- PASS: TestStreetAddress (0.00s)
=== RUN   TestPostCode
--- PASS: …
```

Fix issue #31

---

faker.go

Currently `faker.IntBetween` uses the global rand instance (`rand.Intn`). The global rand instance is always seeded to 1 and as a result `IntBetween` generates the same value every time the program runs. This also causes issues in many other faker methods that use `IntBetween` in their implementation. This change fixes this by using the `Faker.Generator` field instead.
N/A
**Go Version**
```
$ go version
go version go1.15.6 darwin/amd64
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 0.130s
```

fix: Use faker rand instance instead of global rand for IntBetween

---

faker.go

Fixing `Int()` to generate int values different from max(int), noticed by @Hedgehogues in #47
The current implementation of Int() was generating only max values, making that any generator that depends from it (like struct.go) also was affected, this PR fix this behavior.
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 0.011s
```

Fixed bug where Int() was generating only max values

---

faker.go
lorem_flickr.go
lorem_flickr_test.go
person.go
person_test.go
profile_image.go
profile_image_test.go

1. Adding ProfileImage generator to generate profile pictures using the remote service https://thispersondoesnotexist.com/.
1. Added `Image()` method to Person, make it possible to use `faker.Person().Image()` to generate a profile picture 
1. Fixed also some conflicts with the LoremFlickr generator.
Don't apply
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 0.695s
```

Adding ProfileImage generator to generate profile pictures

---

internet.go

Fixing a bug where the StatusCodeWithMessage() method was using a value out of the range of the string list, causing some tests randomly failing when this happens, [example](https://github.com/jaswdr/faker/runs/2492040456) of occurence.
StatusCodeWithMessage raising an out of range exception
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 0.718s
```

Fix StatusCodeWithMessage to not use index out of range

---

phone.go

Changed E164Number function to exclude 0 as a first digit of a number since it's an invalid country code.
[E164Number generates invalid E164 phone number](https://github.com/jaswdr/faker/issues/59)
**Go Version**
```
$ go version
go version go1.15.2 linux/amd64
```
**Go Tests**
```
$ go test
PASS
ok  	github.com/jaswdr/faker	1.193s
```

Fixed E164Number to generate a phone number that doesn't start with 0

---

lorem_flickr.go
profile_image.go
utils.go

We are seeing some timeout transient errors in tests that do http requests to remote services, this PR adds a retry logic by retrying the call 7 times before giving up.
Fixing possible transient failures when calling remote services.
**Go Version**
```
$ go version
go version go1.14.5 darwin/amd64
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 1.387s
```

Adding retry logic for methods that do HTTP requests

---

lorem_flickr.go
profile_image.go

Change `Url` to `URL` in variable names.
Minor fixes to variables names.
**Go Version**
```
$ go version
```
**Go Tests**
go version go1.14.5 darwin/amd64
```
$ go test
PASS
ok      github.com/jaswdr/faker 1.972s
```

Fix variable names

---

payment.go

Make use of `faker.Numerify` method instead of rely on Int numbers, to avoid build errors in 32 bits machines.
Fixing #65 
**Go Version**
```
$ go version
go version go1.14.5 darwin/amd64
```
**Go Tests**
```
$ go test
PASS
ok  	github.com/jaswdr/faker	1.592s
```

Fix #65 by generating card numbers using the Numerify method

---

currency_test.go

Allowing empty string in code generated by Currency generator
**Go Version**
```
$ go version
go version go1.14.5 darwin/amd64
```
**Go Tests**
```
$ go test
PASS
ok  	github.com/jaswdr/faker	1.297s
```

Allowing empty string in code generated by Currency generator

---

faker.go
faker_test.go

I added a calling function to generate a random string of a certain length.
#81
**Go Version**
```
abc@c63bccef3747:~/workspace/oss/faker$ go version
go version go1.17.3 linux/amd64
```
**Go Tests**
```
abc@c63bccef3747:~/workspace/oss/faker$ go test
2022/01/24 00:14:32 Transport: unhandled response frame type *http.http2UnknownFrame
PASS
ok      github.com/jaswdr/faker 53.795s
```
(The warning should be from another test that is unrelated to this added functionality)

feat: added RandomStringWithLength

---

faker_test.go
internet.go
internet_test.go

As reported in #83 some emails names were invalid due to the fact that some first names have `"`, like `O"Connol`. This change fixes that by only allowing valid characters and improve the detection by validating the email address in tests.
Fixing #83
**Go Version**
```
$ go version
go version go1.17.3 linux/amd64
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 0.779s
```

Fixing #83 by handling invalid e-mail names

---

faker.go
faker_test.go

Fixing **IntBetween** by handling edge case where math.MaxInt is used as maximum value.
#85 and #87 seems to be related.
**Go Version**
```
$ go version
go version go1.17.6 linux/amd64
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker 0.937s
```

Handling edge case in IntBetween when using MaxInt

---

currency_test.go
faker_test.go

Fixing `currency.go` tests.
No.
**Go Version**
```
$ go version
go version go1.18.2 linux/amd64
```
**Go Tests**
```
$ go test
ok      github.com/jaswdr/faker 1.194s
```

Fixing Currency test and add ExpectInInt and ExpectInString test helpers

---

binarystring.go
binarystring_test.go
company.go
company_test.go

Use string builders instead of a string in functions that uses for loops to concatenate data. Here is the comparison between the main branch and this one. Data generated by benchstat.
```
name                  old time/op  new time/op  delta
BinaryString-8        7.78µs ± 0%  3.61µs ± 0%   ~     (p=1.000 n=1+1)
CompanyCatchPhrase-8   311ns ± 0%   226ns ± 0%   ~     (p=1.000 n=1+1)
CompanyBS-8            315ns ± 0%   231ns ± 0%   ~     (p=1.000 n=1+1)
```
Yes #101 
**Go Version**
```
$ go version
go version go1.11 darwin/amd64
```
**Go Tests**
```
$ go test
ok  	faker	6.307s
```

Improve performance using a string builder instead of a string

---

.github/workflows/test.yml

Adding Go version 1.19.x to test matrix, to validate that the library is compatible.
N/A
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
```

Add Go 1.19.x to test matrix

---

directory.go
directory_test.go
faker.go
file.go
file_test.go
utils.go
utils_test.go

This PR adds fake directories to file.go, including tests. 
No
**Go Version**
```
$ go version
```
**Go Tests**
```
➜  faker git:(file_directories) ✗ go test -v -run "TestDriveLetter|TestAbsolutePath|TestDirectory"
=== RUN   TestDirectory
--- PASS: TestDirectory (0.00s)
=== RUN   TestDriveLetter
--- PASS: TestDriveLetter (0.00s)
=== RUN   TestAbsolutePath
--- PASS: TestAbsolutePath (0.00s)
PASS
ok      github.com/jaswdr/faker 0.004s
➜  faker git:(file_directories) ✗ GOOS=windows go test -v -run "TestDriveLetter|TestAbsolutePath|TestDirectory"
=== RUN   TestDirectory
--- PASS: TestDirectory (0.00s)
=== RUN   TestDriveLetter
--- PASS: TestDriveLetter (0.00s)
=== RUN   TestAbsolutePath
--- PASS: TestAbsolutePath (0.00s)
PASS
ok …
```

Added fake Directories and Absolute File Paths 

---

faker.go
faker_test.go

Add UintBetween* generators.
Fixes #125
**Go Version**
```
$ go version
go version go1.14.3 darwin/amd64
```
**Go Tests**
```
$ go test
2022/12/25 11:06:17 Error while requesting https://loremflickr.com/300/200 : request failed
2022/12/25 11:06:17 Error while creating a temp file: temp file creation failed
2022/12/25 11:06:18 Error while requesting https://thispersondoesnotexist.com/image : request failed
2022/12/25 11:06:18 Error while creating a temp file: temp file creation failed
PASS
ok      github.com/jaswdr/faker 2.597s
```

[FEATURE] Add methods for uints

---

faker.go

Signature of function Uint(8/16/32/64)Between is replaced from int params to uint params. 
Also for more idiomatic way that methods now calling to base UIntBetween instead of IntBetween.
**Go Version**
```
$ go version
go version go1.19.5 darwin/arm64
```
**Go Tests**
```
$ go test
2023/02/27 21:59:56 Error while requesting https://loremflickr.com/300/200 : request failed
2023/02/27 21:59:57 Error while creating a temp file: temp file creation failed
2023/02/27 21:59:58 Error while requesting https://thispersondoesnotexist.com/image : request failed
2023/02/27 21:59:58 Error while creating a temp file: temp file creation failed
PASS
ok      github.com/jaswdr/faker 5.998s
```

Fix signature of UintBetween generator functions

---

faker.go
internet.go
lorem.go
person.go
pet.go
user_agent.go

Cache array operations to reduce memory utilization and CPU time associated with heap management.  faker is now no longer in the hot path when generating random data.

memoize various read-only arrays

---

uuid.go

I changed the way the Variant bits were set in method V4() of uuid.go
I'm trying to fix issue #134
The variant bits are set to RFC4122 by AND-ing the original bits with 0x3f and OR-ing them with 0x80.
Now, each time you run the code, it should generate a random UUID version 4
**Go Version**
```
$ go version
go version go1.19.5 windows/amd64   
```
**Go Tests**
```
$ go test
=== RUN   TestUUIDv4
--- PASS: TestUUIDv4 (0.00s)
PASS
ok      github.com/jaswdr/faker 0.034s
=== RUN   TestUUIDV4UniqueInSequence
--- PASS: TestUUIDV4UniqueInSequence (0.00s)
PASS
ok      github.com/jaswdr/faker 0.025s
```

Update the Variant bits in method V4() of uuid.go

---

utils.go

Removing usage of deprecated io/ioutil module.
[DeepSource violation](https://app.deepsource.com/gh/jaswdr/faker/issue/GO-W1009/occurrences?listindex=0)
**Go Version**
```
$ go version
go version go1.21.4 linux/amd64
```
**Go Tests**
```
$ go test
ok  	github.com/jaswdr/faker
```

Removed usage of deprecated io/ioutil module.

---

faker.go
faker_test.go

based on #160 
- faker: fix panic from int wraparound when Intn(math.MaxInt+1)
- Refactoring code, renaming rndInt to value and removing unreachable code

fix intn panic

---

faker.go
faker_test.go

This reverts commit ae23891d4c901b3603aad44fa0bba41cf0735f84.
Re-applying fix of potential panic that could happen when generating int values.
Reverting #165
**Go Version**
```
$ go version
go version go1.21.5 darwin/arm64
```
**Go Tests**
```
$ go test ./...
ok  	github.com/jaswdr/faker/v2	3.687s
```

fix intn panic (#163)

---

faker.go
faker_test.go

Change the way Int* and UInt* are generated to avoid returning only 0s.
fixes #164
**Go Version**
```
$ go version
go version go1.21.6 linux/amd64
```
**Go Tests**
```
$  go test ./...
ok      github.com/jaswdr/faker/v2
```

Fix Int* and UInt* return only 0s

---

faker_test.go
random_element.go
random_element_test.go
time.go

Currently, there are `RandomStringElement` and `RandomIntElement` methods in the package, but what happens if e.g. we want to select one of the users that are of type `type User struct{...}`, we may need a generic random select function and that's the reason I implemented RandomElement function.
Also, what happens if we want to give more chances to some elements? I added RandomElementWeighted for that purpose.
+ Added required test cases for previous functions and a test for `RandomStringElement`
Unfortunately, due to golang lack of support for typed parameters, these new two functions couldn't be methods and are implemented as functions taking Faker as argument (not receiver).
-----
There was also a small change in `time.ISO8601` function for how we format the time, as …

add: random element and weighted random element.

---

payment.go
payment_test.go

Fix credit card expiration date.
The generated expiration dates were in date/month format when they should be in month/year format.
Also, the month generated was between 12 and 30 when it should have been between 1 and 12.
This issue is not reported in github.
**Go Version**
```
$ go version
go version go1.22.2 darwin/amd64
```
**Go Tests**
```
$ go test
2024/04/24 17:23:36 Error while requesting https://loremflickr.com/300/200 : request failed
2024/04/24 17:23:36 Error while creating a temp file: temp file creation failed
2024/04/24 17:23:36 Error while requesting https://randomuser.me : request failed
2024/04/24 17:23:36 Error while creating a temp file: temp file creation failed
PASS
ok  	github.com/jaswdr/faker/v2	1.668s
```

Fix credit card expiration date

---

.github/workflows/test.yml

As stated in README, only the last 2 versions of Go are supported
N/A
**Go Version**
N/A
**Go Tests**
N/A

Removing tests run for Go 1.20.x

---

faker.go
faker_test.go

Fix the float functions to return the proper number of decimals, based off of the maxDecimals argument. Prior to this fix, a random value was generated between 0 and `maxDecimals` and that was used as the decimal portion. This meant that values generated with maxDecimals=2, the decimal portion of all generated values would be either `.0`, `.1` or `.2`, instead of there being 2 digits in the decimal portion. With the fix, values generated with maxDecimals=2 will have a decimal portion anywhere between `.00` and `.99`, inclusively.
Missing tests were also added for `Float`, `Float32` and `Float64`
https://github.com/jaswdr/faker/issues/177
**Go Version**
```
$ go version
go version go1.23.2 darwin/arm64
```
**Go Tests**
```
$ go …
```

fix: Float functions should return the proper number of decimals

---

address.go

Remove unnecessary `%` character from building number.
#180

Remove % from address building number

---

random_element.go
random_element_test.go

Add two generic functions, analog to to RandomStringMapKey and RandomStringMapValue, in the same way RandomElement is to RandomStringElement.
This was something I felt was missing as I was trying to get a random map element from a map than was not a `map[string]string`.
Unlike their String counterpart though, no sorting is performed. Doing a sort would require the generics to be constrained to `cmd.Ordered` which I feel is too restrictive.
No
**Go Version**
```
$ go version
go version go1.23.2 darwin/arm64
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker/v2      7.547s
```

feat: Add RandomMapKey and RandomMapValue

---

struct.go
struct_test.go

- Added FillWithDepth method to allow specifying maximum recursion depth for nested structs.
- Improved fillValue method to handle recursive structures and nested arrays.
- Updated tests to cover new functionality, including child structures and nested arrays with fakesize.
- Enhanced existing tests for clarity and coverage of various struct types.
Fix stack overflow when attempting to use recursive structs.
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
ok      github.com/jaswdr/faker/v2      2.448s
```

feat: Enhance struct filling with recursive support and depth control

---

faker.go
pokemon.go
pokemon_test.go

Adding a new random generation set: Pokemon name
Why?
I love the library, but needed Japanese text for some of my organisation's tests. Pokemon names seemed to be the easiest and most appropriate way to make this happen
No
**Go Version**
```
$ go version
go version go1.23.6 linux/amd64
```
**Go Tests**
```
$ go test
2025/04/30 14:00:23 Error while requesting https://loremflickr.com/300/200 : request failed
2025/04/30 14:00:23 Error while creating a temp file: temp file creation failed
2025/04/30 14:00:23 Error while requesting https://randomuser.me : request failed
2025/04/30 14:00:23 Error while creating a temp file: temp file creation failed
PASS
ok      github.com/jaswdr/faker/v2      5.438s
```

feat: add pokemon names

---

.github/workflows/test.yml
faker_test.go
utils.go

- Eliminated unnecessary rounding assertions in TestRandomFloat, TestFloat, TestFloat32, and TestFloat64 to streamline test logic and improve clarity.
N/A
**Go Version**
```
$ go version
```
**Go Tests**
```
$ go test
PASS
ok      github.com/jaswdr/faker/v2      2.558s
```

refactor: Remove redundant float rounding checks in tests

---

.github/workflows/codeql-analysis.yml

CodeQL V1 is now deprecated, this PR is bumping it to V2 to re-enable quality checks.
CodeQL V1 deprecation.
**Go Version**
N/A
**Go Tests**
N/A

Bump CodeQL version to V2

---

faker.go

The logic inside was the exact opposite of the description.
It could only return digits in the ignore list 🤦
**Go Version**
```
$ go version
go version go1.24.1 darwin/arm64
```
**Go Tests**
```
$ go test
2025/07/19 20:59:40 Error while requesting https://loremflickr.com/300/200 : request failed
2025/07/19 20:59:41 Error while creating a temp file: temp file creation failed
2025/07/19 20:59:41 Error while requesting https://randomuser.me : request failed
2025/07/19 20:59:41 Error while creating a temp file: temp file creation failed
PASS
ok  	github.com/jaswdr/faker/v2	2.462s
```

Fixed RandomDigitNot function

---

struct.go
struct_test.go

Add the ability to register custom functions and use them to dynamically set fields in a struct. This is done by setting the `fake` tag on a struct field to `fn=some_function` and then calling `faker.RegisterFunction("some_function", func() interface{} {...})`. When `fake.Struct().Fill(&o)` is called, it will call the registered function and use that value to fill the struct. If the return value of the function can't be assigned to the field, the normal logic will be used.
No
**Go Version**
```
$ go version
go version go1.24.5 darwin/arm64
```
**Go Tests**
```
$ go test
2025/07/17 09:59:07 Error while requesting https://loremflickr.com/300/200 : request failed
2025/07/17 09:59:07 Error while creating a temp file: temp file …
```

Add support for user specified functions for structs

---

README.md

Correct the mention to require Go 1.22 as minimum version in README.
N/A
**Go Version**
N/A
**Go Tests**
N/A

Correct minimum Go version in README
